name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
on:
  push:
    branches:
      - master
 
env:
  VERSION: ${{ github.run_number }}
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/66snowden/devsecops-training:mario-game-1.0.0
          docker save -o supermariolatestdockerimage.tar docker.io/66snowden/devsecops-training:mario-game-1.0.0

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: 'supermariolatestdockerimage.tar'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
 
